### PR TITLE
Milestone: Friendships v2 

### PR DESCRIPTION
**Pull request by newhorizon-tech**
- Improve the efficiency of FriendshipRequest data model  
- Used "reverse friendship" model to make queries faster
- Refactored code for models and controllers
- Added unit testing
- Added integration testing

Tools used:
-  RSpec
-  Capybara 
-  Selenium

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 
- Please extend the Pull Request message to include a summary of the new concepts you learned in this milestone.
- Please move your accept/reject friendship methods to your friendship model. Also, in this milestone, these should include the creation of a complementary "reverse friendship" record in the database. You may use something like this as a pattern:
```
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
``` 
- For hints on how to implement this, check out the following articles:

> - https://explainextended.com/2009/03/07/selecting-friends/
> - https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table

- Please use something like this as a relationship for your User model:
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- Please add some integration tests with Capybara to automate testing your log-in, post, etc forms.

***[OPTIONAL[***

- Consider defining User#pending_friends as an association with SQL query instead of processing objects in application memory (query data it is always more efficient than ruby)

## However, there are some changes required 👀 🧰 🔨 🔧 

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well so far. Most of the required changes have been made.
However, some changes are still needed before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] In `app/models/user.rb`, you now have 2 relationships named `friends`. 
- There's one at line 13 and another one at line 16. 
- I believe one of them is redundant. Kindly check for the one you're using and remove the unnecessary one (probably the one at line 13).

- [x] You have some logic in your view files.
- View files like `app/views/users/_user.html.erb` and `app/views/users/show.html.erb` have embedded logic in them. Kindly separate view-related logic using the helper module.

- [x] I'm having the error below when I tried to run your test cases.
spec




* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Hi @newhorizon-tech  & @tnyandoro,
This is looking good. You've done a great job so far, However, there seems to be a semantic error in your friend request behavior. Let's quickly dive in and fix this!__

**[ REQUIRED CHANGES ]**

- [ ] Something seems to be wrong with the friend request feature.
- Assume we have 2 users (user1 & user2). Let's say `user1` sends a friend request to `user2`. If this is the case, a single record should be created in the friendship table, with `user1.id` as `user_id` and `user2.id` as `friend_id` and finally, `status` as `false`. Then when `user2` confirms the friend request sent by `user1`, the status of the first record should change to `true`, and also another record is created in the `friendship` table, with `user2.id` as `user_id` and `user1.id` as `friend_id`, and finally, the `status` is set to `true`
- Your project does not have the flow above. From my understanding, here's your project flow
  - When user1 sends a request to user2, there's no link or button present for user2 to accept or reject the friend request.
  - I believe this button was present before, but maybe during your recent refactoring and all, something went wrong.
  - Kindly check this bug and ensure that users can confirm friend requests sent to them.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Comment by tnyandoro** [comment]
Milestone completed

**Pull request merged**
